language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

script:
  - npm install && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  target-branch: master
  local_dir: build
  on:
    tags: true